safe area 원복 및 하단 safe area 제거
depromeet/ygtang-app pull request #80
Opened 2022-06-18 07:21 UTC by positiveko

# ⛳️작업 내용

safe area원복 합니다. 대신 이번에는 하단 safe-area는 해제합니다.
# 📸스크린샷

![image](https://user-images.githubusercontent.com/69200669/174427426-d88cda30-b9c3-4b13-8afc-097af7893824.png)
![image](https://user-images.githubusercontent.com/69200669/174427438-822e8433-01c1-40e4-b67e-506dc46aa669.png)

# ⚡️사용 방법

# 📎레퍼런스

2022-06-18 07:41 UTC, ddarkr requested changes

2022-06-18 07:41 UTC, ddarkr commented on src/screens/HomeScreen.tsx
> -      <YgtStatusBar />
엇 요거 삭제되면 안드로이드에서 상단바가 이상하게 표시될 것 같아요! YgtStatusbar 자체는 유지해주셔야 될 듯 합니다 ㅠㅠ

2022-06-18 09:15 UTC, hyesungoh approved these changes
👍 👍 👍 도현님이 코멘트 남겨주신 것만 확인해주시면 좋을 거 같아요 ~!

2022-06-19 08:06 UTC, positiveko commented on src/screens/HomeScreen.tsx
> -      <YgtStatusBar />
아 도현님 이거 app에도 있는데 home에도 유지해야하나요~?

2022-06-19 08:43 UTC, ddarkr commented on src/screens/HomeScreen.tsx
> -      <YgtStatusBar />
아 app에도 있나요? 전역에 있으면 빼버려도 좋을 듯 합니다!

2022-06-19 08:56 UTC, positiveko commented on src/screens/HomeScreen.tsx
> -      <YgtStatusBar />
아하 네! Home이랑 App에 둘 다 들어가있어서 홈에 있는 걸 제거했어요 아이폰은 제대로 뜨는 것 확인했어요! 작업하시면서 안드로 문제 발생하면 말씀해주세요~~

2022-06-19 09:12 UTC, ddarkr approved these changes

2022-06-19 12:36 UTC, merged