feat: 안드로이드 백 버튼 핸들링, 웹뷰 리팩토링
depromeet/ygtang-app pull request #88
Opened 2022-06-21 12:25 UTC by ddarkr

# ⛳️작업 내용

- 안드로이드 백 버튼 이슈를 해결합니다.
- 웹뷰 컴포넌트를 만들고 리팩토링하였습니다.

Closed #84 
Closed #85 
Closed #87 

# 📸스크린샷

# ⚡️사용 방법

# 📎레퍼런스

2022-06-21 14:44 UTC, positiveko requested changes
도현님 요거 린트 에러가 있네요! 확인해 보셔야 할 것 같아요~

2022-06-21 17:21 UTC, hyesungoh approved these changes
👍 👍 👍 👍 👍 👍

리팩토링 도사 도현님 따봉드립니다 👍

2022-06-21 17:36 UTC, SenseCodeValue approved these changes
감사합니다!! 제 코드로 컨플릭트...부탁드립니다!!

2022-06-22 11:18 UTC, ddarkr commented on src/components/ShareHandler.tsx
> +      event.canGoForward &&
리팩토링을 도와준 젯브레인에게 영광을 돌립니다

2022-06-22 12:03 UTC, positiveko approved these changes

2022-06-22 12:04 UTC, merged